# Generated by Django 2.2.10 on 2020-08-28 11:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bettertexts', '0011_auto_20200527_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='comment_form_intro',
            field=ckeditor.fields.RichTextField(blank=True, max_length=20000, verbose_name='comment form intro'),
        ),
    ]
