# Generated by Django 2.2.3 on 2020-08-31 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bettertexts', '0012_type_comment_form_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='type',
            name='comment_form_intro',
            field=models.TextField(blank=True, max_length=20000, verbose_name='comment form intro'),
        ),
    ]
