# Generated by Django 2.2.3 on 2020-08-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bettertexts', '0013_auto_20200831_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='thanks',
            field=models.TextField(blank=True, default='Thanks for your reaction!', max_length=2000, verbose_name='thanks text'),
        ),
    ]
