# Generated by Django 2.2.3 on 2020-08-31 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bettertexts', '0014_type_thanks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='thanks',
            field=models.CharField(blank=True, default='Bedankt voor je reactie!', max_length=2000, verbose_name='thanks text'),
        ),
    ]
