# Generated by Django 2.2.3 on 2020-08-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bettertexts', '0015_auto_20200831_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='inform_label',
            field=models.CharField(blank=True, max_length=200, verbose_name='inform label'),
        ),
        migrations.AddField(
            model_name='type',
            name='involved_label',
            field=models.CharField(blank=True, max_length=200, verbose_name='involved label'),
        ),
    ]
