# Generated by Django 2.2.3 on 2020-09-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bettertexts', '0016_auto_20200831_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='rating_type',
            field=models.CharField(choices=[('S', 'Stars'), ('P', 'Points')], default='S', max_length=2, verbose_name='rating type'),
        ),
    ]
